openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:9090
    description: Generated server url
paths:
  /client/save:
    post:
      tags:
        - client-controller
      operationId: saveClient
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClientDtoRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ClientDtoResponse"
  /client/id:
    post:
      tags:
        - client-controller
      operationId: getClientById
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClientIdentifierDtoRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ClientEntity"
components:
  schemas:
    ClientDtoRequest:
      required:
        - birthDate
        - email
        - firstSurname
        - gender
        - name
        - phone
        - secondSurname
      type: object
      properties:
        name:
          type: string
        firstSurname:
          type: string
        secondSurname:
          type: string
        birthDate:
          type: string
          format: date
        gender:
          type: string
          enum:
            - MALE
            - FEMALE
        email:
          type: string
        phone:
          type: string
    ClientDtoResponse:
      type: object
      properties:
        clientId:
          type: integer
          format: int64
    ClientIdentifierDtoRequest:
      type: object
      properties:
        id:
          minimum: 1
          type: integer
          format: int64
    ClientEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        firstSurname:
          type: string
        secondSurname:
          type: string
        birthDate:
          type: string
          format: date
        gender:
          type: string
          enum:
            - MALE
            - FEMALE
        email:
          type: string
        phone:
          type: string
